export const BANKINFO_REQUEST_PENDING = 'BANKINFO_REQUEST_PENDING';
export const BANKINFO_REQUEST_SUCCESS = 'BANKINFO_REQUEST_SUCCESS';
export const BANKINFO_REQUEST_FAILED = 'BANKINFO_REQUEST_FAILED';
export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const CHANGE_CITY = 'CHANGE_CITY';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const CHANGE_RESULTS_PER_PAGE = 'CHANGE_RESULTS_PER_PAGE';

export const URL = 'https://vast-shore-74260.herokuapp.com/banks?city=MUMBAI';